### ISSUE TITLE
K线图的Kline模块咨询

### ISSUE THREAD

**Issue by stone3536** [msincenselee/vnpy#12]
## Issue类型
三选一：Question

## 重现步骤

大佳，您好
对kline下文件进行了下了解，还是非常复杂的，恳请您百忙中指导下，谢谢！
发在issue这里是希望后来也能够用到您的包的人也看到这个文档，这样可以节省您些时间也能让开始接触的人快速了解。

### **一、对K线图想要实现的效果**
1、实现K线图的多个标的叠加使用，比如“价差和对应腿leg1、leg2、leg3”都显示在一个图上，左边是百分比，右边是价差的值，横轴是时间，此种情况就不需要指标了，仅仅是为了看到价差和对应腿的变化情况，价差的价格变化主要是由哪个腿变化导致的。
同时实现历史数据和tick时时更新显示。

2、实现单个K线图及指标多个周期图显示，这个功能其实1实现了这个就试下了；

### **二、对kline浏览后的理解：**
1、文件kline_widgets.py 中的类“class RenkoKline”与“class MultiKlineWindow”分别是可以实现窗口显示；
2、文件kline.py 中的类“class GridKline”“ class MultiKlineWindow(QtWidgets.QMainWindow)”也可以实现窗口显示；
（这里不知道是否理解正确，如有理解错误，恳请您指导下，谢谢！）

试着运行了\tests\renko 下的“ui_renko_reverse_klines.py”
报错，部分错误信息如下：
File "E:\00_VNPY_2.x\Anaconda3\lib\site-packages\pandas\io\parsers.py", line 1
853, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 387, in pandas._libs.parsers.TextReader.
__cinit__
  File "pandas/_libs/parsers.pyx", line 705, in pandas._libs.parsers.TextReader.
_setup_parser_source
FileNotFoundError: [Errno 2] File b'log/renko_reverse_v1_J99_M15.csv' does not e
xist: b'log/renko_reverse_v1_J99_M15.csv'

对于以上是否有单独的可以运行起来的demo实例？是否可以将文件中用到的csv的文件及可以运行起来的测试数据和对应的脚本共享下？
用txd还是比较麻烦点儿的，如果必须得用txd才跑的更好，是否可以提供下这方面的资料供我学习并跑起来，感谢！

另外还请您指导下，上边1、2中的，我具体该用哪个更合适？ 另外看了后有个困惑就是如何才能实现时时tick更新生成bar呢？
我是想结合到目前最新的vnpy2.1.9中使用。

### **三、component的理解、缺少的文件**
试着运行component下的test的2个文件，分别报错，其中test_line_bar_02.py的报错信息如下：
Traceback (most recent call last):
  File "test_line_bar_02.py", line 392, in <module>
    csvfile = open(filename, 'r', encoding='utf8')
FileNotFoundError: [Errno 2] No such file or directory: 'E:\\00_VNPY_2.x\\Anacon
da3\\Lib\\bar_data\\J99_20160101_1m.csv'

找了下压缩包中，没有发现类似的csv数据文件，请问是否可以提供下这类的测试数据文件以及能够跑起来的脚本，谢谢！

如果数据文件及对应脚本没办法发上来，麻烦您发下邮件吧。
另外是否有这部分KLINE模块和component的更详细的文档说明是否方便发送？
在文件中看到您也实现了缠论的图形分析的，对这部分如何显示出来，是否有特殊要求？

问的有点儿多，恳请您百忙中指导下，感恩，谢谢！

邮箱：11516469@qq.com

**Comment by msincenselee** [comment]
这个图表类，对实时行情支持不是太在行，我没有去细调实时行情。
我一般用它在回测的结果展示分析，还有查看策略的当前所有K线（如果你是多K线的话），或者查看切片。

**Comment by stone3536** [comment]
大佳老师，您好
请问，是否可以提供对应的数据模板，这样方便进行debug看下具体逻辑；
切片的尝试看了下，修改了几个地方，仍旧无法下载切片数据，所以一直也显示不出来切片对应的K线图的；

可否提供几个你用到的数据模板带数据的，好用来分析逻辑的时候debug使用，谢谢！

周末原来电脑坏了，今天才装好新的电脑得空上来看下的。
