### ISSUE TITLE
直接使用报停止单self.strategy.onStopOrder(so)的错误

### ISSUE THREAD

**Issue by luhongkai** [msincenselee/vnpy#4]
use module file:D:\backtests\vnpy-master\vnpy-master\vnpy\trader\.\VT_setting.json
load ctaBase.py
init D:\backtests\vnpy-master\vnpy-master\vnpy\trader\app\ctaStrategy\strategy
loading vnpy.trader.app.ctaStrategy.strategy.strategyAtrRsi
adding AtrRsiStrategy into STRATEGY_CLASS
finished load strategy modules
use module file:D:\backtests\vnpy-master\vnpy-master\vnpy\trader\app\ctaStrategy\.\CTA_setting.json
2018-08-30 14:25:12.684219      开始载入数据
2018-08-30 14:25:12.712220      载入完成，数据量：21656
2018-08-30 14:25:12.712220      开始回测
2018-08-30 14:25:12.712220      策略初始化完成
2018-08-30 14:25:12.712220      策略启动完成
2018-08-30 14:25:12.712220      开始回放数据
Traceback (most recent call last):

  File "<ipython-input-10-da419b2f4be2>", line 1, in <module>
    runfile('D:/backtests/vnpy-master/vnpy-master/vnpy/trader/app/ctaStrategy/strategy/strategyAtrRsi.py', wdir='D:/backtests/vnpy-master/vnpy-master/vnpy/trader/app/ctaStrategy/strategy')

  File "D:\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 705, in runfile
    execfile(filename, namespace)

  File "D:\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "D:/backtests/vnpy-master/vnpy-master/vnpy/trader/app/ctaStrategy/strategy/strategyAtrRsi.py", line 271, in <module>
    engine.runBacktesting()

  File "D:\backtests\vnpy-master\vnpy-master\vnpy\trader\app\ctaStrategy\ctaBacktesting.py", line 250, in runBacktesting
    func(data)

  File "D:\backtests\vnpy-master\vnpy-master\vnpy\trader\app\ctaStrategy\ctaBacktesting.py", line 262, in newBar
    self.strategy.onBar(bar)    # 推送K线到策略中

  File "D:/backtests/vnpy-master/vnpy-master/vnpy/trader/app/ctaStrategy/strategy/strategyAtrRsi.py", line 226, in onBar
    orderID = self.cover(shortStop, abs(self.pos), stop=True)

  File "D:\backtests\vnpy-master\vnpy-master\vnpy\trader\app\ctaStrategy\ctaTemplate.py", line 123, in cover
    return self.sendOrder(CTAORDER_COVER, price, volume, stop)

  File "D:\backtests\vnpy-master\vnpy-master\vnpy\trader\app\ctaStrategy\ctaTemplate.py", line 131, in sendOrder
    vtOrderIDList = self.ctaEngine.sendStopOrder(self.vtSymbol, orderType, price, volume, self)

  File "D:\backtests\vnpy-master\vnpy-master\vnpy\trader\app\ctaStrategy\ctaBacktesting.py", line 516, in sendStopOrder
    self.strategy.onStopOrder(so)

  File "D:\backtests\vnpy-master\vnpy-master\vnpy\trader\app\ctaStrategy\ctaTemplate.py", line 103, in onStopOrder
    raise NotImplementedError

NotImplementedError

**Comment by msincenselee** [comment]
在策略.py中做个onStopOrder接口实现
